name: Continuos Integration

#trigger que dispara o pipeline
on: [pull_request, push]

jobs:
  continuos-integration:
    runs-on: ubunto-latest

  steps:
    - uses: action/checkout@v3
    - name: Using Node.js
      uses: actions/setup-nome@v2
      with:
        node-version: 24.x
    - name: run install, build, test and deploy
      run: |
        npm install
        npm run build
        npm run test
        npm run deploy