name: Continuos Integration

# trigger que dispara o pipeline
on: [pull_request, push]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Using Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: run install, build, test and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Define o token como vari√°vel de ambiente
        run: |
          npm install
          CI=false npm run build
          npm run test
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          # O comando abaixo passa o token diretamente para o script gh-pages
          npm run deploy -- -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git