name: Continuos Integration

# trigger que dispara o pipeline
on: [pull_request, push]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Using Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.

      - name: run install, build, test and deploy
        run: |
          npm install
          CI=false npm run build
          npm test -- --passWithNoTests
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          # Injeta o token na URL remota para permitir o push
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          npm run deploy